//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballTicketOfficeAPI.Data
{
    using FootballTicketOfficeAPI.Models;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int Sector { get; set; }
        public int Row { get; set; }
        public int Site { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public int MatchId { get; set; }
        public bool Status { get; set; }
        [JsonIgnore]
        public virtual Client Client { get; set; }
        [JsonIgnore]
        public virtual Match Match { get; set; }
        public ClientTicketResponse toClientTicketResponse()
        {
            return new ClientTicketResponse()
            {
                Id = Id,
                ClientId = ClientId,
                Sector = Sector,
                Row = Row,
                Site = Site,
                PurchaseDate = PurchaseDate,
                MatchId = MatchId,
                Status = Status,
                match = Match.toMatchResponse()
            };
        }

    }
}
